name: jaguar_file_saver
version: 0.0.1
description: File saver interceptor and utilities for Dart
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  #jaguar:
    # path: ../jaguar
  #  git: https://github.com/Jaguar-dart/jaguar.git

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
